import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`grid min-h-screen place-items-center bg-slate-200 text-7xl font-extrabold tracking-tight text-indigo-600`}
      >
        PBC LIFE
      </main>
    </>
  );
}
