name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations @${{ github.actor }} on creating your very first issue in GitOpener! 🎉 Thank you for taking the initiative to share your thoughts and ideas with us. Your contribution is highly appreciated and we look forward to collaborating with you to make this project even better. Keep up the good work!'
          pr-message: 'Congratulations @${{ github.actor }} on creating your very first pull request in GitOpener! 🎉 Your hard work and dedication to this project is truly appreciated. Thank you for your valuable contribution and for helping us move one step closer to achieving our goals. Keep up the awesome work!'
